services:
  syte_pipeline:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - syte_net
    volumes:
      - syte_data:/opt/data
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - MAX_WORKERS=1
      - SYTE_LOCAL_DIR=/opt/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  postgis:
    image: postgis/postgis:16-3.4
    restart: on-failure
    platform: linux/amd64
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_DB: ${db}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${user} -d ${db}']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - syte_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - syte_net

networks:
  syte_net:
    driver: bridge


volumes:
  syte_data:
    external: true